site_name: Wyliodrin Documentation
site_description: Description of libwyliodrin's functions and visual blocks used in Wyliodrin
theme: readthedocs
use_directory_urls: false
pages:
- Overview: 'index.md'
- libwyliodrin:
    - 'Constants': 'constants.md'
    - 'Functions': 'functions.md'
    
