site_name: Wyliodrin Documentation
site_description: Description of libwyliodrin's functions and visual blocks used in Wyliodrin
theme: readthedocs
use_directory_urls: false
pages:
- Overview: 'index.md'
- libwyliodrin:
    - 'Constants': 'constants.md'
    - 'Peripheral Control': 'functions.md'
    - 'Time': 'timing.md'
    - 'Math': 'math.md'
    - 'Bits and Bytes': 'bits.md'
    - 'SPI Communication': 'spi.md'
    - 'I2C Communication': 'i2c.md'
    - 'Signals': 'signal.md'
    - 'Board Communication': 'communication.md'
